Added php 7.0
cloudposse/apache-php pull request #1
Opened 2017-11-27 07:33 UTC by goruha

## What
* Use php 7.0
* Enabled travis ci 
* Refactor dir structure

## Why
* Need php 7.0 for one project
* To build containers the same way
* To follow on pattern for containers repo structure

2017-11-27 08:11 UTC, osterman approved these changes
What about suhosin? We use it to lock down php on Wordpress

2017-11-27 08:11 UTC, osterman requested changes
See comment about suhosin

2017-11-27 09:54 UTC, goruha commented
There is no suhosin for php7.0
https://github.com/sektioneins/suhosin7
It does not looks like production ready.

2017-11-28 18:18 UTC, osterman approved these changes

2017-11-29 06:54 UTC, merged